name: Playwright Tests

on:
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |  
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install Playwright browsers
        run: playwright install
      - name: Create env file
        run: |
          touch .env
          echo TEST_EMAIL=${{ vars.TEST_EMAIL }} >> .env
          echo TEST_PASSWORD=${{ vars.TEST_PASSWORD }} >> .env
      - name: Lint with mypy
        run: mypy .
      - name: Run tests
        run: pytest --tracing=retain-on-failure --alluredir=allure-results ./tests --numprocesses 2
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/